### ISSUE TITLE
[New Package]: Baidu.BaiduSIMeeting

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal9/winget-pkgs-automation#393]
### List the PackageIdentifier of the package to be added to automation

Baidu.BaiduSIMeeting

### Details about the application

https://fanyiapp.cdn.bcebos.com/tongchuan/update/latest.yml
```Yaml
version: 2.0.1
files:
  - url: BaiduTongchuan_setup_2.0.1.exe
    sha512: dVoN5mtUgvFgM3jpLFQ3qiMzXMhPojD0XupWx7orsQ5xximVX9tFn4bLFHJ5dI3AfvnGMij8sXW8FVeRTb2ZGA==
    size: 52343983
path: BaiduTongchuan_setup_2.0.1.exe
sha512: dVoN5mtUgvFgM3jpLFQ3qiMzXMhPojD0XupWx7orsQ5xximVX9tFn4bLFHJ5dI3AfvnGMij8sXW8FVeRTb2ZGA==
releaseDate: '2020-11-10T03:15:55.641Z'
```
