### ISSUE TITLE
[Feature/Idea]: Beta tracks on winget-automation

### ISSUE THREAD

**Issue by CodeDoctorDE** [vedantmgoyal9/winget-pkgs-automation#459]
### What would you like to see changed/added?

https://github.com/microsoft/winget-pkgs/pull/60088#issuecomment-1123589502

Add two different types of releases. Beta and stable

**Comment by CodeDoctorDE** [comment]
And an option to specify the exact version:
```yml
name: Publish to WinGet
on: [release]
jobs:
  publish-stable:
    if: ${{ github.ref == 'refs/tags/stable' }}
    runs-on: windows-latest
    steps:
      - name: Get version
        id: version
        shell: bash
        run: |
          BUTTERFLY_VERSION_REGEX="version:\s(.+)\+(.+)"
          [[ $(grep -E "${BUTTERFLY_VERSION_REGEX}" app/pubspec.yaml) =~ ${BUTTERFLY_VERSION_REGEX} ]]
          BUTTERFLY_VERSION="${BASH_REMATCH[1]}"
          echo "BUTTERFLY_VERSION=${BUTTERFLY_VERSION}" >> $GITHUB_ENV
```
I want to use `${{ env.BUTTERFLY_VERSION }}` as release
