### ISSUE TITLE
[New Package]: OpenJS.NodeJS.Nightly 19.0.0

### ISSUE THREAD

**Issue by russellbanks** [vedantmgoyal9/winget-pkgs-automation#524]
### List the PackageIdentifier of the package to be added to automation

OpenJS.NodeJS.Nightly

### Details about the application

I've been updating this package manually myself but it would be good if it can be automated.

Source: https://nodejs.org/download/nightly/
Source JSON: https://nodejs.org/download/nightly/index.json

The JSON file doesn't provide the links directly but does provide values that can create the url. It provides an array of the nightly versions, and is ordered by date, so the url should be able to be created by getting the first index of the array (the newest version), getting the version string (e.g. v19.0.0-nightly2022060985f8821f4d) and putting it together would be something like this:

```yaml
https://nodejs.org/download/nightly/${Response[0].version}/node-${Response[0].version}-$architecture.msi
```

For example, the nightly release for today, 9th June 2022, would be:
```yaml
Package Version: 19.0.0
x64 Installer URL: https://nodejs.org/download/nightly/v19.0.0-nightly2022060985f8821f4d/node-v19.0.0-nightly2022060985f8821f4d-x64.msi
x86 Installer URL: https://nodejs.org/download/nightly/v19.0.0-nightly2022060985f8821f4d/node-v19.0.0-nightly2022060985f8821f4d-x86.msi
```
